version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_chess
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123456/"
      POSTGRES_DB: chess-application
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 