version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_chess
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123456/"
      POSTGRES_DB: chess-application
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chessnet
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: chessai-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@test.com
      PGADMIN_DEFAULT_PASSWORD: "123456/"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - chessnet
    restart: unless-stopped

networks:
  chessnet:

volumes:
  postgres_data:
  pgadmin_data:
