name: Newman API Tests

on:
  push:
    branches:
      - main
      - miro
  pull_request:
    branches:
      - main
      - miro

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Start Docker Compose
        working-directory: ./ChessAI
        run: docker compose up -d

      - name: Start backend server
        run: mvn spring-boot:run &
        working-directory: ChessAI

      - name: Wait for backend to start
        run: sleep 20

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run API Tests
        run: |
          newman run ChessAI/src/test/postman/ChessAI.postman_collection.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: newman-report.html
